// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMWRR.Data;

#nullable disable

namespace TMWRR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250820011212_MoveToTMUFCampaignScoresSnapshot")]
    partial class MoveToTMUFCampaignScoresSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TMWRR.Entities.TMUFCampaign", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("TMUFCampaigns");
                });

            modelBuilder.Entity("TMWRR.Entities.TMUFCampaignScoresSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedAt")
                        .IsUnique();

                    b.ToTable("TMUFCampaignScoresSnapshots");
                });

            modelBuilder.Entity("TMWRR.Entities.TMUFCampaignScoresSnapshot", b =>
                {
                    b.HasOne("TMWRR.Entities.TMUFCampaign", "Campaign")
                        .WithMany("ScoresSnapshots")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("TMWRR.Entities.TMUFCampaign", b =>
                {
                    b.Navigation("ScoresSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
