// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMWRR.Data;

#nullable disable

namespace TMWRR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TMWRR.Entities.Game", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("TMWRR.Entities.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorScore")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorTime")
                        .HasColumnType("int");

                    b.Property<string>("DeformattedName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EnvironmentId")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MapUid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ModeId")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("NbLaps")
                        .HasColumnType("int");

                    b.Property<byte[]>("Thumbnail")
                        .HasMaxLength(512000)
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("MapUid");

                    b.HasIndex("ModeId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("TMWRR.Entities.Mode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Modes");
                });

            modelBuilder.Entity("TMWRR.Entities.TMEnvironment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("TMWRR.Entities.TMFCampaign", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("TMFCampaigns");
                });

            modelBuilder.Entity("TMWRR.Entities.TMFCampaignScoresRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("DrivenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MapId")
                        .HasColumnType("int");

                    b.Property<byte>("Order")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("PlayerId")
                        .HasColumnType("varchar(32)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("TMFCampaignScoresRecords");
                });

            modelBuilder.Entity("TMWRR.Entities.TMFCampaignScoresSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("NoChanges")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedAt")
                        .IsUnique();

                    b.ToTable("TMFCampaignScoresSnapshots");
                });

            modelBuilder.Entity("TMWRR.Entities.TMFLogin", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TMFLogins");
                });

            modelBuilder.Entity("TMWRR.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginTMFId")
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("LoginTMFId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TMWRR.Entities.Map", b =>
                {
                    b.HasOne("TMWRR.Entities.User", "Author")
                        .WithMany("Maps")
                        .HasForeignKey("AuthorId");

                    b.HasOne("TMWRR.Entities.TMEnvironment", "Environment")
                        .WithMany("Maps")
                        .HasForeignKey("EnvironmentId");

                    b.HasOne("TMWRR.Entities.Mode", "Mode")
                        .WithMany("Maps")
                        .HasForeignKey("ModeId");

                    b.Navigation("Author");

                    b.Navigation("Environment");

                    b.Navigation("Mode");
                });

            modelBuilder.Entity("TMWRR.Entities.TMEnvironment", b =>
                {
                    b.HasOne("TMWRR.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TMWRR.Entities.TMFCampaignScoresRecord", b =>
                {
                    b.HasOne("TMWRR.Entities.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMWRR.Entities.TMFLogin", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId");

                    b.HasOne("TMWRR.Entities.TMFCampaignScoresSnapshot", "Snapshot")
                        .WithMany("Records")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("Player");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("TMWRR.Entities.TMFCampaignScoresSnapshot", b =>
                {
                    b.HasOne("TMWRR.Entities.TMFCampaign", "Campaign")
                        .WithMany("ScoresSnapshots")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("TMWRR.Entities.User", b =>
                {
                    b.HasOne("TMWRR.Entities.TMFLogin", "LoginTMF")
                        .WithMany("Users")
                        .HasForeignKey("LoginTMFId");

                    b.Navigation("LoginTMF");
                });

            modelBuilder.Entity("TMWRR.Entities.Mode", b =>
                {
                    b.Navigation("Maps");
                });

            modelBuilder.Entity("TMWRR.Entities.TMEnvironment", b =>
                {
                    b.Navigation("Maps");
                });

            modelBuilder.Entity("TMWRR.Entities.TMFCampaign", b =>
                {
                    b.Navigation("ScoresSnapshots");
                });

            modelBuilder.Entity("TMWRR.Entities.TMFCampaignScoresSnapshot", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("TMWRR.Entities.TMFLogin", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TMWRR.Entities.User", b =>
                {
                    b.Navigation("Maps");
                });
#pragma warning restore 612, 618
        }
    }
}
